### ISSUE TITLE
Something Went Wrong message when posting

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2015group6#209]
I tried to create a post under Adnan Syed with the following content:

Adnan Syed become well known after a wildly popular podcast called Serial, a spin-off from the popular radio show/podcast "This American Life".

He was convicted of murdering his class-mate and x girlfriend in 1999. His case brings forth many issues, such as memory, jury system, racism, islamaphobia, justice, and much more. 

He is a child of immigrants from Pakistan and his girlfriend Hae Min Lee was Korean.

with tags:

convict
murder
serial podcast
pakistan

I tried by posting when the topic is selected:
Adnan Syed
Group: Person

from the Post tab.

I also tried from graph mode. 

I get the same popup.
---

It gives me "Something Went Wrong" message, which seems the only error message that one gets (thus, no idea what is going on).

**Comment by temelkandaz** [comment]
Thanks for reporting the bug.

We checked on our end and understood that it is a backend issue. Posts are stored as regular strings in database so because you basically exceed the maximum amount of characters that a string can take it gives out an error. 

Our backend team will change the data type of the column so that we will allow user to create longer posts.

We will keep you updated.

**Comment by hamzaozturk** [comment]
We had a problem with post character limit. We solved this problem and posted your text succesfully. You can see your post under the Adnan Syed topic with tags you mentioned.

**Comment by temelkandaz** [comment]
Suzan Hocam, please confirm that the fix works.
