### ISSUE TITLE
A user can up vote a post as much as they want

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2015group6#210]
As uskudarli I upvoted Jury System over 100 all at once. 

A user should have only 1 vote per item.

**Comment by temelkandaz** [comment]
Thanks for reporting the bug.

However we were already aware of this; we are using rating and post count of topic to increase the size of the topics in graph. So in this alpha version of our website we thought that it would be easier to upVote to a higher number with one user rather than creating 20 users to rate a topic to 20. 

Since there are many topics with different sizes in the graph now. We can change this feature.

We will keep you updated.

**Comment by temelkandaz** [comment]
Hello again.

I am happy to say that we fixed this bug. Now, a user have only 1 vote per item.

Please test the rating mechanism and confirm if we can close this issue.

Thanks.

**Comment by uskudarli** [comment]
I would not call it a feature, just for convenience sake. In fact, it is a bad idea, leading to poor testing.

In order to create data for such apps, what we really want is scripts that create lots of data programmatically and not via user interaction (for creating a rich set of data of reasonable size) 

Back to the main point, tested, works fine. Closing the issue. Yeay, another one down!
