### ISSUE TITLE
Something Went Wrong message shows up often even when things seem to have worked

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2015group6#212]
I so often see the popup "Something Went Wrong" and have no idea what is going on. There is no information. 

Eventually I see that sometimes it seems to have worked even though I saw an error.

For example, I created a new topic called Software Engineering. When I tried to create it, the system gave me the error. When I tried again, it said that the "Topic already exists". I checked, and saw it did indeed exist.

Something is very strange about the "Something went wrong error". Pops up all over the place, with no way to understand what is going on.

**Comment by temelkandaz** [comment]
While creating a topic from the graph view user needs to separate the tags with a comma. Whenever a user tries a different way to create a topic with tags server gives out a 500 error. Because tags are used in too many places in our application wrongly entered tags are causing server to give out 500 error in too many different processes.

On the other hand, "Something Went Wrong" errors are implications of the 500 Internal Server Error which user shouldn't have an information about. For other situations we have different messages such as "Topic Already Exist" or "Wrong username/password"  and different ways of dealing with wrong inputs such as disabling submit buttons or changing the color of an input text to red if an unexpected input is taken.

I hope this answers your question.
